version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - django
      - next
    restart: unless-stopped

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mariadb
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: next
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: devdb
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpass
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped