FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y default-libmysqlclient-dev
COPY . .

CMD ["sh", "-c", "python manage.py migrate && python manage.py createsu && python manage.py runserver 0.0.0.0:8000"]

